{% set name = "sunode" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pymc-devs/sunode/archive/v{{ version }}.tar.gz
  sha256: 72eebe5a5ab41371ac075174c791ab198b74dfeaa4342721b9ee6ecbfef7719b


build:
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"
  # osx_64 builds fail, see:
  #   <https://github.com/conda-forge/sunode-feedstock/pull/35>
  #   <https://github.com/pymc-devs/pytensor/pull/725>
  # also python 3.8 fails on linux64 with:
  #   <https://github.com/conda-forge/sunode-feedstock/pull/27#issuecomment-1991217351>
  skip: true  # [(py<=37) or (linux64 and py<=38) or (osx and x86_64)]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cffi                                   # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - liblapack
    - cffi
    - sundials >=5.3,<6.0
  run:
    - python
    - cffi
    - xarray
    - scipy
    - sundials >=5.3,<6.0
    - numba >=0.57
    - typing_extensions
    - sympy >=1.8

test:
  imports:
    - sunode
  requires:
    - pytest
    - hypothesis
    - statsmodels
    - pip
    - pytensor
  commands:
    - pip check
    - pytest --pyargs sunode

about:
  home: https://github.com/pymc-devs/sunode
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Python interface to sundials with support for derivatives and PyMC'

  doc_url: https://sunode.readthedocs.io/
  dev_url: https://github.com/pymc-devs/sunode

extra:
  recipe-maintainers:
    - aseyboldt
    - michaelosthege
