{% set name = "sunode" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/aseyboldt/sunode/archive/v{{ version }}.tar.gz
  sha256: 39beecc0ff345403160abb21a5b61649d3f66bcf53704b5311c9970c9ef6cac5

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<37]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cffi
    - sundials >=5.3
  run:
    - python
    - numpy >=1.14
    - cffi
    - xarray >=0.15
    - scipy
    - sundials >=5.3
    - numba >=0.49
    - typing_extensions
    - sympy

test:
  imports:
    - sunode
  requires:
    - pytest
    - hypothesis
    - statsmodels
    - pip
  commands:
    - pip check
    - pytest --pyargs sunode

about:
  home: https://github.com/aseyboldt/sunode
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python interface to sundials with support for derivatives and PyMC3

  doc_url: https://sunode.readthedocs.io/
  dev_url: https://github.com/aseyboldt/sunode

extra:
  recipe-maintainers:
    - aseyboldt
    - michaelosthege
