{% set name = "sunode" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pymc-devs/sunode/archive/v{{ version }}.tar.gz
  sha256: 7c82b3872625052e537fe8099f69bf3b73169e8d560e2f07de7d9103753d1cbc


build:
  number: 2
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: True  # [py<37]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy >=1.17
    - liblapack
    - cffi
    - sundials >=5.3,<6.0
  run:
    - python
    - numpy >=1.17
    - cffi
    - xarray >=0.15
    - scipy
    - sundials >=5.3,<6.0
    - numba >=0.55.2
    - typing_extensions
    - sympy >=1.8

test:
  imports:
    - sunode
  requires:
    - pytest
    - hypothesis
    - statsmodels
    - pip
    - pytensor
  commands:
    - pip check
    - pytest --pyargs sunode

about:
  home: https://github.com/pymc-devs/sunode
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Python interface to sundials with support for derivatives and PyMC'

  doc_url: https://sunode.readthedocs.io/
  dev_url: https://github.com/pymc-devs/sunode

extra:
  recipe-maintainers:
    - aseyboldt
    - michaelosthege
