{% set name = "sunode" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pymc-devs/sunode/archive/v{{ version }}.tar.gz
  sha256: e4da57f7ffec7b85277fd8847a3d3340f5c162278e6659c1591586f16c0385cd


build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: True  # [py<=37]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cffi                                   # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - liblapack
    - cffi
    - sundials >=5.3,<6.0
  run:
    - python
    - cffi
    - xarray
    - scipy
    - sundials >=5.3,<6.0
    - numba >=0.57
    - typing_extensions
    - sympy >=1.8

test:
  imports:
    - sunode
  requires:
    - pytest
    - hypothesis
    - statsmodels
    - pip
    - pytensor
  commands:
    - pip check
    - pytest --pyargs sunode

about:
  home: https://github.com/pymc-devs/sunode
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Python interface to sundials with support for derivatives and PyMC'

  doc_url: https://sunode.readthedocs.io/
  dev_url: https://github.com/pymc-devs/sunode

extra:
  recipe-maintainers:
    - aseyboldt
    - michaelosthege
